XCCDF-Results to HDF
mitre/heimdall_tools pull request #103
Opened 2021-06-07 20:15 UTC by zacharylc-mitre

* Added hyperlinks to README.md
* Added mapping tool for SCC XCCDF-Results to HDF
* Made changes to heimdall_tools.rb and cli.rb to account for xccdf_mapper

Fixes #95

Signed-off-by: zacharylc <zacharylc@mitre.org>

2021-06-08 15:31 UTC, Bialogs commented
needs a rebase

2021-06-09 21:16 UTC, Bialogs reviewed
Needs a review by @ejaronne

2021-06-11 18:47 UTC, ejaronne commented
The SCC xml sample doesn't seem to produce the check-content field, as seen in the base (non-results) xccdf of the STIG. Otherwise, mappings look correct. Is it possible to see a generic expected xccdf results xml that isn't generated by any particular client? Otherwise, I fear this has been tailored to SCC's own special XML interpretation, and therefore should be renamed "SCC-xxcdf-mapper"

Actual STIG:
![image](https://user-images.githubusercontent.com/34140975/121735203-cb1c6000-cac3-11eb-9704-0d74665ea0ca.png)

Sample from SCC (lacks Check Text):
![image](https://user-images.githubusercontent.com/34140975/121735297-ebe4b580-cac3-11eb-85ae-2c3c4e43c3f8.png)

2021-06-16 20:15 UTC, rx294 commented
@zacharylc-mitre Please resolve merge conflicts on the Readme

2021-06-16 20:18 UTC, rx294 commented
@zacharylc-mitre I agree with @ejaronne that the scope should be limited to SCC xccdf type.

Possibly `scc_xccdf_mapper` is the correct title ... @aaronlippold @Bialogs please add you thoughts.

Besides `xccdf_results_mapper` breaks your current naming pattern.

2021-06-16 20:27 UTC, rx294 requested changes
Just the naming change and associated metadata changes..

mapper code LTGM

2021-06-16 20:27 UTC, rx294 commented on README.md
> +13. [**xccdf_results_mapper**](#xccdf_results_mapper) - SCC Client XCCDF-Results scans
Update to `SCC Compliance Validation tool`

2021-06-17 00:17 UTC, Bialogs commented
It was originally named xccdf_mapper which I renamed to xccdf_results because the XCCDF schema and the XCCDF-results schema are different. Can we point to a SCC XCCDF-Results schema? I'm trying to call it what it is. Maybe we just call it an SCC mapper.

2021-06-17 13:06 UTC, ejaronne commented
Eventually, @aaronlippold wanted this to translate any client that generates the xccdf_results format. This has only been tested to convert SCC output. I agree though that leading with xccdf_results_mapper will go over the heads of many non-data-schema folks who just want that "SCAP mapper", but won't see it. How about we revamp: 

The upper list should have links to the converters later in the README.

In the upper list, put in an entry called "SCC (SCAP Compliance Checker) results mapper", but link it to the xccdf_results_mapper later in the README. As the xccdf_results_mapper adapts to work with other SCAP validated tools such as OpenSCAP, place a *new* entry in the upper list, but link it to the *same* xcddf_results_mapper lower on the list.

2021-06-17 15:22 UTC, rx294 commented
Adding some notes for info

looks like `test-system` field identifies the test tool that generated xccdf

**openscap**
`
        <TestResult xmlns="http://checklists.nist.gov/xccdf/1.2" id="xccdf_org.open-scap_testresult_xccdf_mil.disa.stig_profile_MAC-1_Public" start-time="2021-06-16T16:01:29-05:00" end-time="2021-06-16T16:01:37-05:00" version="001.001" test-system="cpe:/a:redhat:openscap:1.3.4">
`

**scc**
`
      <cdf:TestResult start-time="2021-04-29T14:16:20" end-time="2021-04-29T14:24:10" id="xccdf_mil.disa.stig_testresult_scap_mil.disa.stig_comp_U_RHEL_7_V3R2_STIG_SCAP_1-2_Benchmark-xccdf.xml---xccdf_mil.disa.stig_profile_MAC-1_Classified-1" version="003.002" test-system="cpe:/a:spawar:scc:5.4">
`

`test-system` seems to be universal field

https://csrc.nist.rip/library/alt-SP800-126r3.pdf
_section: 4.5 XCCDF Results_

2021-06-17 15:22 UTC, rx294 commented
Taking back my objection re `xccdf_results_mapper`

2021-06-17 18:12 UTC, Bialogs commented
Okay so it seems the way ahead should just update the README to be clear

2021-06-17 19:02 UTC, merged